"""
conftest.py — Shared test fixtures (PostgreSQL)
=================================================
Uses a real local PostgreSQL database (b2b_exceptions_test).
Each test function uses a session-level transaction that rolls back.
"""

from __future__ import annotations

import os
import sys
from decimal import Decimal

import pytest
from sqlalchemy import create_engine
from sqlalchemy.orm import Session, sessionmaker

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from backend.app.models.db import (
    Account,
    AccountTier,
    Base,
    Inventory,
    Order,
    OrderStatus,
    WarehouseCode,
)

TEST_DB_URL = os.getenv(
    "TEST_DATABASE_URL",
    "postgresql+psycopg2://vishvmunjapara@localhost:5432/b2b_exceptions_test",
)


@pytest.fixture(scope="session")
def db_engine():
    """Create the test engine once, drop & recreate all tables."""
    engine = create_engine(TEST_DB_URL, echo=False)
    Base.metadata.drop_all(engine)
    Base.metadata.create_all(engine)
    yield engine
    Base.metadata.drop_all(engine)
    engine.dispose()


@pytest.fixture(scope="function")
def db_session(db_engine):
    """Fresh session per test. Uses SAVEPOINT for rollback isolation."""
    connection = db_engine.connect()
    transaction = connection.begin()
    session = Session(bind=connection)

    yield session

    session.close()
    if transaction.is_active:
        transaction.rollback()
    connection.close()


@pytest.fixture(scope="function")
def seeded_session(db_session: Session):
    """
    Session pre-populated with seed data.
    Account IDs are dynamic (auto-generated by PG).
    """
    accounts = [
        Account(company_name="Acme Distribution Co.", tier=AccountTier.STANDARD),
        Account(company_name="BulkTrade Wholesale LLC", tier=AccountTier.WHOLESALE),
        Account(company_name="Premium Partners Inc.", tier=AccountTier.VIP),
    ]
    db_session.add_all(accounts)
    db_session.flush()

    inventory = [
        Inventory(sku="WIDGET-001", warehouse_code=WarehouseCode.WH_A, quantity=500),
        Inventory(sku="WIDGET-001", warehouse_code=WarehouseCode.WH_B, quantity=300),
        Inventory(sku="GADGET-002", warehouse_code=WarehouseCode.WH_A, quantity=150),
        Inventory(sku="GADGET-002", warehouse_code=WarehouseCode.WH_B, quantity=0),
        Inventory(sku="SPROCKET-003", warehouse_code=WarehouseCode.WH_A, quantity=1200),
        Inventory(sku="SPROCKET-003", warehouse_code=WarehouseCode.WH_B, quantity=800),
    ]
    db_session.add_all(inventory)
    db_session.flush()

    orders = [
        Order(
            account_id=accounts[0].id,
            sku="WIDGET-001",
            ordered_quantity=600,
            calculated_total=Decimal("11994.00"),
            status=OrderStatus.PENDING,
            error_log='{"error": "quantity_exceeds_single_warehouse"}',
        ),
        Order(
            account_id=accounts[1].id,
            sku="GADGET-002",
            ordered_quantity=200,
            calculated_total=Decimal("2898.00"),
            status=OrderStatus.PENDING,
            error_log='{"error": "warehouse_B_out_of_stock"}',
        ),
        Order(
            account_id=accounts[2].id,
            sku="SPROCKET-003",
            ordered_quantity=50,
            calculated_total=Decimal("499.50"),
            status=OrderStatus.PENDING,
            error_log='{"error": "tier_pricing_mismatch"}',
        ),
    ]
    db_session.add_all(orders)
    db_session.flush()

    # Store references for easy access in tests
    db_session._test_accounts = accounts
    db_session._test_orders = orders

    yield db_session
